import '../models/crop.dart';

class CropDataService {
  static final CropDataService _instance = CropDataService._internal();
  factory CropDataService() => _instance;
  CropDataService._internal();

  List<Crop> _crops = [];

  List<Crop> get crops => _crops;

  void initializeCrops() {
    _crops = _getAllCrops();
  }

  List<Crop> _getAllCrops() {
    return [
      // Vegetables
      Crop(
        id: 'tomato',
        name: 'Tomato',
        scientificName: 'Solanum lycopersicum',
        category: 'Vegetable',
        description: 'A popular warm-season vegetable rich in lycopene and vitamin C.',
        biology: CropBiology(
          minTemperature: 15,
          maxTemperature: 30,
          optimalTemperature: 22,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 75,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 150,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 6.8,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Spring', 'Summer'],
      ),
      Crop(
        id: 'potato',
        name: 'Potato',
        scientificName: 'Solanum tuberosum',
        category: 'Vegetable',
        description: 'A staple crop grown for its starchy tubers.',
        biology: CropBiology(
          minTemperature: 7,
          maxTemperature: 25,
          optimalTemperature: 18,
          minSoilMoisture: 70,
          maxSoilMoisture: 85,
          optimalSoilMoisture: 75,
          daysToMaturity: 90,
          germinationDays: 14,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 4.8,
          phMax: 5.5,
          optimalPh: 5.2,
          sunlightHours: 6,
        ),
        growingSeasons: ['Spring', 'Fall'],
      ),
      Crop(
        id: 'corn',
        name: 'Corn',
        scientificName: 'Zea mays',
        category: 'Grain',
        description: 'A major cereal grain crop used for food, feed, and biofuel.',
        biology: CropBiology(
          minTemperature: 10,
          maxTemperature: 30,
          optimalTemperature: 21,
          minSoilMoisture: 50,
          maxSoilMoisture: 70,
          optimalSoilMoisture: 60,
          daysToMaturity: 90,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 5.8,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Spring', 'Summer'],
      ),
      Crop(
        id: 'rice',
        name: 'Rice',
        scientificName: 'Oryza sativa',
        category: 'Grain',
        description: 'A staple food for more than half of the world population.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 35,
          optimalTemperature: 28,
          minSoilMoisture: 80,
          maxSoilMoisture: 100,
          optimalSoilMoisture: 90,
          daysToMaturity: 120,
          germinationDays: 5,
          minRainfall: 100,
          maxRainfall: 200,
          soilType: 'Clay',
          phMin: 5.0,
          phMax: 7.5,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Spring', 'Summer'],
      ),
      Crop(
        id: 'wheat',
        name: 'Wheat',
        scientificName: 'Triticum aestivum',
        category: 'Grain',
        description: 'One of the most important cereal crops worldwide.',
        biology: CropBiology(
          minTemperature: 3,
          maxTemperature: 25,
          optimalTemperature: 15,
          minSoilMoisture: 40,
          maxSoilMoisture: 60,
          optimalSoilMoisture: 50,
          daysToMaturity: 120,
          germinationDays: 7,
          minRainfall: 30,
          maxRainfall: 80,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.8,
          sunlightHours: 6,
        ),
        growingSeasons: ['Fall', 'Winter', 'Spring'],
      ),
      Crop(
        id: 'carrot',
        name: 'Carrot',
        scientificName: 'Daucus carota',
        category: 'Vegetable',
        description: 'A root vegetable rich in beta-carotene and vitamin A.',
        biology: CropBiology(
          minTemperature: 7,
          maxTemperature: 25,
          optimalTemperature: 18,
          minSoilMoisture: 60,
          maxSoilMoisture: 75,
          optimalSoilMoisture: 65,
          daysToMaturity: 75,
          germinationDays: 14,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Sandy',
          phMin: 6.0,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 6,
        ),
        growingSeasons: ['Spring', 'Fall'],
      ),
      Crop(
        id: 'onion',
        name: 'Onion',
        scientificName: 'Allium cepa',
        category: 'Vegetable',
        description: 'A bulb vegetable used as a flavoring agent in many cuisines.',
        biology: CropBiology(
          minTemperature: 7,
          maxTemperature: 25,
          optimalTemperature: 18,
          minSoilMoisture: 50,
          maxSoilMoisture: 70,
          optimalSoilMoisture: 60,
          daysToMaturity: 100,
          germinationDays: 10,
          minRainfall: 30,
          maxRainfall: 80,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 6,
        ),
        growingSeasons: ['Spring', 'Fall'],
      ),
      Crop(
        id: 'cabbage',
        name: 'Cabbage',
        scientificName: 'Brassica oleracea',
        category: 'Vegetable',
        description: 'A leafy green vegetable rich in vitamins K and C.',
        biology: CropBiology(
          minTemperature: 4,
          maxTemperature: 24,
          optimalTemperature: 18,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 80,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.8,
          sunlightHours: 6,
        ),
        growingSeasons: ['Spring', 'Fall', 'Winter'],
      ),
      Crop(
        id: 'pepper',
        name: 'Bell Pepper',
        scientificName: 'Capsicum annuum',
        category: 'Vegetable',
        description: 'A sweet pepper variety rich in vitamin C.',
        biology: CropBiology(
          minTemperature: 18,
          maxTemperature: 30,
          optimalTemperature: 24,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 75,
          germinationDays: 10,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Spring', 'Summer'],
      ),
      Crop(
        id: 'cucumber',
        name: 'Cucumber',
        scientificName: 'Cucumis sativus',
        category: 'Vegetable',
        description: 'A refreshing vegetable with high water content.',
        biology: CropBiology(
          minTemperature: 18,
          maxTemperature: 30,
          optimalTemperature: 24,
          minSoilMoisture: 70,
          maxSoilMoisture: 85,
          optimalSoilMoisture: 75,
          daysToMaturity: 60,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Spring', 'Summer'],
      ),
      Crop(
        id: 'bean',
        name: 'Green Bean',
        scientificName: 'Phaseolus vulgaris',
        category: 'Legume',
        description: 'A legume vegetable rich in protein and fiber.',
        biology: CropBiology(
          minTemperature: 15,
          maxTemperature: 27,
          optimalTemperature: 21,
          minSoilMoisture: 50,
          maxSoilMoisture: 70,
          optimalSoilMoisture: 60,
          daysToMaturity: 55,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 6,
        ),
        growingSeasons: ['Spring', 'Summer'],
      ),
      Crop(
        id: 'lettuce',
        name: 'Lettuce',
        scientificName: 'Lactuca sativa',
        category: 'Vegetable',
        description: 'A leafy green vegetable commonly used in salads.',
        biology: CropBiology(
          minTemperature: 4,
          maxTemperature: 20,
          optimalTemperature: 15,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 45,
          germinationDays: 7,
          minRainfall: 30,
          maxRainfall: 80,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 4,
        ),
        growingSeasons: ['Spring', 'Fall', 'Winter'],
      ),
      Crop(
        id: 'spinach',
        name: 'Spinach',
        scientificName: 'Spinacia oleracea',
        category: 'Vegetable',
        description: 'A nutrient-dense leafy green rich in iron and vitamins.',
        biology: CropBiology(
          minTemperature: 4,
          maxTemperature: 20,
          optimalTemperature: 15,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 40,
          germinationDays: 7,
          minRainfall: 30,
          maxRainfall: 80,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.8,
          sunlightHours: 4,
        ),
        growingSeasons: ['Spring', 'Fall', 'Winter'],
      ),
      Crop(
        id: 'broccoli',
        name: 'Broccoli',
        scientificName: 'Brassica oleracea var. italica',
        category: 'Vegetable',
        description: 'A cruciferous vegetable rich in vitamins and antioxidants.',
        biology: CropBiology(
          minTemperature: 4,
          maxTemperature: 24,
          optimalTemperature: 18,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 70,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.8,
          sunlightHours: 6,
        ),
        growingSeasons: ['Spring', 'Fall'],
      ),
      Crop(
        id: 'eggplant',
        name: 'Eggplant',
        scientificName: 'Solanum melongena',
        category: 'Vegetable',
        description: 'A warm-season vegetable rich in antioxidants.',
        biology: CropBiology(
          minTemperature: 18,
          maxTemperature: 30,
          optimalTemperature: 24,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 80,
          germinationDays: 10,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 5.5,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Spring', 'Summer'],
      ),
      Crop(
        id: 'squash',
        name: 'Squash',
        scientificName: 'Cucurbita pepo',
        category: 'Vegetable',
        description: 'A versatile summer or winter squash variety.',
        biology: CropBiology(
          minTemperature: 15,
          maxTemperature: 30,
          optimalTemperature: 22,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 60,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Spring', 'Summer'],
      ),
      Crop(
        id: 'radish',
        name: 'Radish',
        scientificName: 'Raphanus sativus',
        category: 'Vegetable',
        description: 'A fast-growing root vegetable with a peppery taste.',
        biology: CropBiology(
          minTemperature: 7,
          maxTemperature: 25,
          optimalTemperature: 18,
          minSoilMoisture: 50,
          maxSoilMoisture: 70,
          optimalSoilMoisture: 60,
          daysToMaturity: 30,
          germinationDays: 5,
          minRainfall: 30,
          maxRainfall: 80,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 6,
        ),
        growingSeasons: ['Spring', 'Fall'],
      ),
      Crop(
        id: 'peas',
        name: 'Peas',
        scientificName: 'Pisum sativum',
        category: 'Legume',
        description: 'A cool-season legume rich in protein and fiber.',
        biology: CropBiology(
          minTemperature: 4,
          maxTemperature: 20,
          optimalTemperature: 15,
          minSoilMoisture: 50,
          maxSoilMoisture: 70,
          optimalSoilMoisture: 60,
          daysToMaturity: 60,
          germinationDays: 7,
          minRainfall: 30,
          maxRainfall: 80,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.8,
          sunlightHours: 6,
        ),
        growingSeasons: ['Spring', 'Fall'],
      ),
      Crop(
        id: 'okra',
        name: 'Okra',
        scientificName: 'Abelmoschus esculentus',
        category: 'Vegetable',
        description: 'A warm-season vegetable with edible seed pods.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 35,
          optimalTemperature: 28,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 60,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 150,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Spring', 'Summer'],
      ),
      Crop(
        id: 'cauliflower',
        name: 'Cauliflower',
        scientificName: 'Brassica oleracea var. botrytis',
        category: 'Vegetable',
        description: 'A cool-season cruciferous vegetable.',
        biology: CropBiology(
          minTemperature: 7,
          maxTemperature: 24,
          optimalTemperature: 18,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 80,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.8,
          sunlightHours: 6,
        ),
        growingSeasons: ['Spring', 'Fall'],
      ),
      // Additional requested crops (restored)
      Crop(
        id: 'sugarcane',
        name: 'Sugarcane',
        scientificName: 'Saccharum officinarum',
        category: 'Industrial',
        description: 'A tropical grass cultivated for sugar production.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 35,
          optimalTemperature: 28,
          minSoilMoisture: 70,
          maxSoilMoisture: 90,
          optimalSoilMoisture: 80,
          daysToMaturity: 300,
          germinationDays: 14,
          minRainfall: 100,
          maxRainfall: 200,
          soilType: 'Loamy',
          phMin: 5.0,
          phMax: 8.0,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'sugar_beet',
        name: 'Sugar beet',
        scientificName: 'Beta vulgaris',
        category: 'Industrial',
        description: 'A temperate root crop used for sugar production.',
        biology: CropBiology(
          minTemperature: 5,
          maxTemperature: 25,
          optimalTemperature: 18,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 180,
          germinationDays: 10,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.8,
          sunlightHours: 6,
        ),
        growingSeasons: ['Spring', 'Fall'],
      ),
      Crop(
        id: 'sweet_potato',
        name: 'Sweet Potato (Kamote)',
        scientificName: 'Ipomoea batatas',
        category: 'Root/Tuber',
        description: 'A starchy, sweet-tasting tuber commonly grown in the tropics.',
        biology: CropBiology(
          minTemperature: 18,
          maxTemperature: 30,
          optimalTemperature: 24,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 120,
          germinationDays: 14,
          minRainfall: 50,
          maxRainfall: 120,
          soilType: 'Sandy Loam',
          phMin: 5.5,
          phMax: 6.5,
          optimalPh: 6.0,
          sunlightHours: 8,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'cassava',
        name: 'Cassava (Kamoteng Kahoy)',
        scientificName: 'Manihot esculenta',
        category: 'Root/Tuber',
        description: 'A staple root crop known for drought tolerance.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 34,
          optimalTemperature: 28,
          minSoilMoisture: 50,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 65,
          daysToMaturity: 270,
          germinationDays: 20,
          minRainfall: 80,
          maxRainfall: 150,
          soilType: 'Sandy Loam',
          phMin: 5.0,
          phMax: 7.0,
          optimalPh: 6.0,
          sunlightHours: 8,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'taro',
        name: 'Taro (Gabi)',
        scientificName: 'Colocasia esculenta',
        category: 'Root/Tuber',
        description: 'A root crop that thrives in moist conditions.',
        biology: CropBiology(
          minTemperature: 18,
          maxTemperature: 30,
          optimalTemperature: 24,
          minSoilMoisture: 80,
          maxSoilMoisture: 100,
          optimalSoilMoisture: 90,
          daysToMaturity: 200,
          germinationDays: 21,
          minRainfall: 100,
          maxRainfall: 200,
          soilType: 'Clay Loam',
          phMin: 5.5,
          phMax: 7.0,
          optimalPh: 6.2,
          sunlightHours: 6,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'yam',
        name: 'Yam (Ube / Dioscorea)',
        scientificName: 'Dioscorea spp.',
        category: 'Root/Tuber',
        description: 'Tropical tuber crops, including purple yam (ube).',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 32,
          optimalTemperature: 26,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 240,
          germinationDays: 21,
          minRainfall: 80,
          maxRainfall: 150,
          soilType: 'Loamy',
          phMin: 5.5,
          phMax: 7.0,
          optimalPh: 6.3,
          sunlightHours: 8,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'mung_bean',
        name: 'Mung bean (Monggo)',
        scientificName: 'Vigna radiata',
        category: 'Legume',
        description: 'A short-duration legume rich in protein.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 35,
          optimalTemperature: 28,
          minSoilMoisture: 50,
          maxSoilMoisture: 70,
          optimalSoilMoisture: 60,
          daysToMaturity: 65,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.8,
          sunlightHours: 6,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'peanut',
        name: 'Peanut (Mani)',
        scientificName: 'Arachis hypogaea',
        category: 'Legume',
        description: 'A legume that develops pods underground.',
        biology: CropBiology(
          minTemperature: 18,
          maxTemperature: 30,
          optimalTemperature: 24,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 120,
          germinationDays: 10,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Sandy',
          phMin: 5.5,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 6,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'pechay',
        name: 'Pechay / Bok choy',
        scientificName: 'Brassica rapa subsp. chinensis',
        category: 'Leafy',
        description: 'A fast-growing leafy vegetable popular in Asian cuisine.',
        biology: CropBiology(
          minTemperature: 12,
          maxTemperature: 24,
          optimalTemperature: 18,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 45,
          germinationDays: 6,
          minRainfall: 40,
          maxRainfall: 90,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.5,
          sunlightHours: 5,
        ),
        growingSeasons: ['Spring', 'Fall'],
      ),
      Crop(
        id: 'kangkong',
        name: 'Kangkong (Water spinach)',
        scientificName: 'Ipomoea aquatica',
        category: 'Leafy',
        description: 'A semi-aquatic leafy vegetable that thrives in moist conditions.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 35,
          optimalTemperature: 28,
          minSoilMoisture: 80,
          maxSoilMoisture: 100,
          optimalSoilMoisture: 90,
          daysToMaturity: 30,
          germinationDays: 5,
          minRainfall: 80,
          maxRainfall: 150,
          soilType: 'Clay Loam',
          phMin: 5.5,
          phMax: 7.5,
          optimalPh: 6.5,
          sunlightHours: 6,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'ampalaya',
        name: 'Ampalaya (Bitter gourd)',
        scientificName: 'Momordica charantia',
        category: 'Vegetable',
        description: 'A climbing vine known for its bitter fruits.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 32,
          optimalTemperature: 26,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 75,
          germinationDays: 8,
          minRainfall: 60,
          maxRainfall: 120,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.8,
          sunlightHours: 7,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'pineapple',
        name: 'Pineapple',
        scientificName: 'Ananas comosus',
        category: 'Fruit',
        description: 'A tropical fruit crop with spiky leaves and sweet fruits.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 32,
          optimalTemperature: 26,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 540,
          germinationDays: 30,
          minRainfall: 60,
          maxRainfall: 120,
          soilType: 'Sandy Loam',
          phMin: 4.5,
          phMax: 6.5,
          optimalPh: 5.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'watermelon',
        name: 'Watermelon',
        scientificName: 'Citrullus lanatus',
        category: 'Fruit',
        description: 'A warm-season vine producing large, juicy fruits.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 32,
          optimalTemperature: 26,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 85,
          germinationDays: 7,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Sandy Loam',
          phMin: 6.0,
          phMax: 7.5,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'papaya',
        name: 'Papaya',
        scientificName: 'Carica papaya',
        category: 'Fruit',
        description: 'A fast-growing tropical fruit tree.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 34,
          optimalTemperature: 28,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 240,
          germinationDays: 14,
          minRainfall: 80,
          maxRainfall: 150,
          soilType: 'Loamy',
          phMin: 5.5,
          phMax: 7.0,
          optimalPh: 6.2,
          sunlightHours: 8,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'chili',
        name: 'Chili',
        scientificName: 'Capsicum spp.',
        category: 'Vegetable',
        description: 'Spicy peppers used as condiment and spice.',
        biology: CropBiology(
          minTemperature: 18,
          maxTemperature: 32,
          optimalTemperature: 26,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 90,
          germinationDays: 10,
          minRainfall: 50,
          maxRainfall: 100,
          soilType: 'Loamy',
          phMin: 6.0,
          phMax: 7.0,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'ginger',
        name: 'Ginger',
        scientificName: 'Zingiber officinale',
        category: 'Spice',
        description: 'A rhizome used widely as a spice and for medicinal purposes.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 32,
          optimalTemperature: 26,
          minSoilMoisture: 70,
          maxSoilMoisture: 90,
          optimalSoilMoisture: 80,
          daysToMaturity: 240,
          germinationDays: 20,
          minRainfall: 80,
          maxRainfall: 150,
          soilType: 'Loamy',
          phMin: 5.5,
          phMax: 7.0,
          optimalPh: 6.2,
          sunlightHours: 6,
        ),
        growingSeasons: ['Summer'],
      ),
      // Fruits added earlier
      Crop(
        id: 'banana',
        name: 'Banana',
        scientificName: 'Musa spp.',
        category: 'Fruit',
        description: 'A perennial tropical fruit crop.',
        biology: CropBiology(
          minTemperature: 18,
          maxTemperature: 34,
          optimalTemperature: 28,
          minSoilMoisture: 70,
          maxSoilMoisture: 90,
          optimalSoilMoisture: 80,
          daysToMaturity: 300,
          germinationDays: 30,
          minRainfall: 100,
          maxRainfall: 200,
          soilType: 'Loamy',
          phMin: 5.5,
          phMax: 7.5,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'mango',
        name: 'Mango',
        scientificName: 'Mangifera indica',
        category: 'Fruit',
        description: 'A tropical fruit tree with sweet, fibrous fruits.',
        biology: CropBiology(
          minTemperature: 20,
          maxTemperature: 36,
          optimalTemperature: 30,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 365,
          germinationDays: 21,
          minRainfall: 75,
          maxRainfall: 150,
          soilType: 'Loamy',
          phMin: 5.5,
          phMax: 7.5,
          optimalPh: 6.5,
          sunlightHours: 8,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'avocado',
        name: 'Avocado',
        scientificName: 'Persea americana',
        category: 'Fruit',
        description: 'A subtropical fruit tree producing nutrient-rich fruits.',
        biology: CropBiology(
          minTemperature: 15,
          maxTemperature: 30,
          optimalTemperature: 22,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 540,
          germinationDays: 28,
          minRainfall: 80,
          maxRainfall: 160,
          soilType: 'Loamy',
          phMin: 5.5,
          phMax: 7.0,
          optimalPh: 6.3,
          sunlightHours: 7,
        ),
        growingSeasons: ['Summer'],
      ),
      Crop(
        id: 'guava',
        name: 'Guava',
        scientificName: 'Psidium guajava',
        category: 'Fruit',
        description: 'A tropical fruit tree known for fragrant fruits rich in vitamin C.',
        biology: CropBiology(
          minTemperature: 18,
          maxTemperature: 32,
          optimalTemperature: 26,
          minSoilMoisture: 60,
          maxSoilMoisture: 80,
          optimalSoilMoisture: 70,
          daysToMaturity: 240,
          germinationDays: 21,
          minRainfall: 60,
          maxRainfall: 120,
          soilType: 'Loamy',
          phMin: 5.0,
          phMax: 7.5,
          optimalPh: 6.5,
          sunlightHours: 7,
        ),
        growingSeasons: ['Summer'],
      ),
    ];
  }

  List<Crop> searchCrops(String query) {
    final trimmed = query.trim();
    if (trimmed.isEmpty) return _crops;
    final tokens = trimmed.toLowerCase().split(RegExp(r"\s+")).where((t) => t.isNotEmpty).toList();
    return _crops.where((crop) {
      final haystack = '${crop.name} ${crop.scientificName} ${crop.category}'.toLowerCase();
      // AND match: all tokens must be present somewhere in the combined text
      return tokens.every((t) => haystack.contains(t));
    }).toList();
  }

  List<Crop> filterByCategory(String category) {
    if (category.isEmpty) return _crops;
    return _crops.where((crop) => crop.category == category).toList();
  }

  Crop? getCropById(String id) {
    try {
      return _crops.firstWhere((crop) => crop.id == id);
    } catch (e) {
      return null;
    }
  }
}
